# Generated by Django 4.2.1 on 2023-06-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TravelVendorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TravelReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_to', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_train_details', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_location', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_location', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_date', models.DateTimeField()),
                ('reporting_time', models.DateTimeField()),
                ('vehicle_type', models.CharField(blank=True, max_length=255)),
                ('vehicle_booked_by', models.CharField(max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_no', models.CharField(max_length=255, null=True)),
                ('bill_date', models.DateTimeField()),
                ('bill_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_reports_department', to='wheels_app.department')),
                ('travel_vendor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_reports_vendor_name', to='wheels_app.travelvendorname')),
            ],
        ),
    ]
