# Generated by Django 4.2.1 on 2023-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wheels_app", "0003_travelreports_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelreports",
            name="bill_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="travelreports",
            name="created_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Creation Date"
            ),
        ),
        migrations.AlterField(
            model_name="travelreports",
            name="reporting_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="travelreports",
            name="travel_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
