# Generated by Django 4.2.1 on 2023-06-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wheels_app", "0005_alter_travelreports_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelreports",
            name="bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
