# Generated by Django 4.2.1 on 2023-06-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wheels_app", "0006_alter_travelreports_bill_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelreports",
            name="bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
    ]
