# Generated by Django 4.2.1 on 2023-06-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wheels_app", "0007_alter_travelreports_bill_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="travelvendorname",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
