# Generated by Django 4.2.1 on 2023-06-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wheels_app", "0008_alter_department_name_alter_travelvendorname_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelreports",
            name="bill_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="travelreports",
            name="reporting_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="travelreports",
            name="travel_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
