services:
  rw_app:
    build: .
    restart: always
    image: reports_wheels_docker_image
    container_name: reports_wheels_docker_container
    # ports:
    #   - 8000:8000
    env_file:
      - .env
    # command: gunicorn --workers 3 --timeout 86400 --bind 0.0.0.0:8004 reports_wheels.wsgi:application
    volumes:
      - .:/reports_wheels
    depends_on:
      - postgres

  postgres:
    build:
      context: ./postgresql
    image: reports_wheels_postgresql_image
    container_name: reports_wheels_postgresql_container
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    # ports:
    #   - 5432:5432

  nginx:
    build:
      context: ./nginx
    image: reports_wheels_nginx_image
    container_name: reports_wheels_nginx_container
    env_file:
      - .env
    restart: always
    ports:
      - 8009:8009
    volumes:
      - ./static:/reports_wheels/static

    # depends_on:
    #   - node

  # node:
  #   image: node:alpine
  #   ports:
  #     - "3000:3000"

  #   volumes:
  #     - .:/reports_wheels

  #   working_dir: /reports_wheels/HTMS_App/static/HTMS_App/js

  #   command: sh -c "npm install && npm run start"
